In [20]:
import numpy as np

In [ ]:
data2 = [[1,2,3,4,5], [6,7,8,9,10]]
arr2 = np.array(data2)

In [ ]:
arr2

In [ ]:
print(arr2)

In [ ]:
arr2 * 10

In [ ]:
arr = np.arange(15)

In [ ]:
arr

In [ ]:
arr = np.arange(15).reshape((3,5))
arr

In [ ]:
arr.T

In [ ]:
arr = np.random.rand(6, 3)
arr

In [ ]:
np.dot(arr.T, arr)

In [ ]:
arr = np.random.randn(5,4)
arr

In [ ]:
arr.mean()

In [ ]:
np.mean(arr)

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.mean(axis=0)

In [23]:
matrix = np.arange(1, 31).reshape(5, 6)

In [24]:
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [25]:
np.max(matrix)

30

In [26]:
np.sum(matrix, axis=1)

array([ 21,  57,  93, 129, 165])

In [27]:
np.mean(matrix, axis=0)

array([13., 14., 15., 16., 17., 18.])

In [28]:
matrix1 = np.arange(1, 13).reshape(3, 4)
matrix2 = np.arange(12, 0, -1).reshape(3, 4)

In [31]:
matrix1.dot(matrix2.T)

array([[100,  60,  20],
       [268, 164,  60],
       [436, 268, 100]])

In [32]:
vector = np.array([10, 20, 30])

In [33]:
scalar = 2

In [34]:
vector * 2

array([20, 40, 60])